# Generated by Django 3.2.12 on 2022-09-10 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='file',
            new_name='file_dir',
        ),
    ]
